import random

CHUCK_NORRIS_JOKES = [
    "Chuck Norris doesn't read books. He stares them down until he gets the information he wants.",
    "Chuck Norris can divide by zero.",
    "Chuck Norris counted to infinity. Twice.",
    "Chuck Norris can slam a revolving door.",
    "Chuck Norris can unscramble an egg.",
    "Chuck Norris can make onions cry.",
    "Chuck Norris can kill two stones with one bird.",
    "Chuck Norris can speak Braille.",
    "Chuck Norris can win a game of Connect Four in three moves.",
    "Chuck Norris can make a Happy Meal cry.",
    "Chuck Norris can do a wheelie on a unicycle.",
    "Chuck Norris can make a snowman melt just by looking at it.",
    "Chuck Norris can make a tree fall just by looking at it.",
    "Chuck Norris can make a computer cry.",
    "Chuck Norris can make a calculator laugh.",
    "Chuck Norris doesn’t wear a watch. He decides what time it is.",
    "When Chuck Norris enters a room, he doesn’t turn the lights on. He turns the dark off.",
    "Chuck Norris can hear sign language.",
    "Chuck Norris beat the sun in a staring contest.",
    "Chuck Norris can strangle you with a cordless phone.",
    "Chuck Norris can build a snowman out of rain.",
    "Death once had a near-Chuck Norris experience.",
    "Chuck Norris can start a fire by rubbing two ice cubes together.",
    "Chuck Norris can drown a fish.",
    "Chuck Norris doesn’t dial the wrong number. You answer the wrong phone.",
    "Chuck Norris can win a staring contest with his eyes closed.",
    "When Chuck Norris throws a boomerang, it doesn’t come back. It’s too scared.",
    "Chuck Norris can sneeze with his eyes open.",
    "Chuck Norris’s shadow has never dared to follow him.",
    "Chuck Norris can do push-ups... on water.",
    "Chuck Norris's tears cure cancer. Too bad he has never cried.",
    "Chuck Norris doesn’t sleep. He waits.",
    "Chuck Norris once roundhouse kicked someone so hard that his foot broke the speed of light.",
    "Chuck Norris can divide zero by zero and get infinity.",
    "The Boogeyman checks his closet for Chuck Norris.",
    "Chuck Norris can win a game of Monopoly without owning any properties.",
    "Chuck Norris can grill ice cubes.",
    "Chuck Norris can hear a butterfly scream.",
    "Chuck Norris can touch MC Hammer.",
    "Chuck Norris's calendar goes straight from March 31st to April 2nd. No one fools Chuck Norris.",
    "Chuck Norris can slam a revolving door twice.",
    "Chuck Norris doesn't use spell check. If he misspells a word, Oxford changes the spelling.",
    "Chuck Norris can tie his shoes with his feet.",
    "Chuck Norris can play the violin... with a piano.",
    "Chuck Norris doesn’t flush the toilet, he scares the crap out of it.",
    "Chuck Norris once made a weeping willow laugh.",
    "Chuck Norris can do a handstand... on clouds.",
    "Chuck Norris counted to negative infinity.",
    "Chuck Norris can sneeze with his mouth closed and eyes open.",
    "Chuck Norris can run a marathon in under an hour... backward.",
    "Chuck Norris can slam a cloud to the ground.",
    "Chuck Norris invented black.",
    "Chuck Norris once hit a home run with a toothpick.",
    "Chuck Norris doesn’t breathe air. He holds it hostage.",
    "Chuck Norris built the hospital he was born in.",
    "Chuck Norris doesn’t mow his lawn. He dares it to grow.",
    "Chuck Norris makes GPS ask him for directions.",
    "Chuck Norris's pulse is measured on the Richter scale.",
    "Chuck Norris can dig a hole through the Earth with a spoon.",
    "Chuck Norris can hear a pin drop... on Mars.",
    "Chuck Norris doesn’t need a parachute. The ground avoids him.",
    "Chuck Norris doesn't age. Time is too afraid to catch up.",
    "Chuck Norris’s keyboard doesn’t have a backspace key. Chuck Norris never makes mistakes.",
    "Chuck Norris can fry an egg on an ice cube.",
    "Chuck Norris can slam a door that's already closed.",
    "Chuck Norris built a time machine and went back in time to stop the Big Bang. It still happened because Chuck let it.",
    "Chuck Norris can hear colors.",
    "Chuck Norris can clean his windows... from the inside of a volcano.",
    "Chuck Norris has a grizzly bear rug. The bear is alive, it's just afraid to move.",
    "Chuck Norris knows Victoria’s secret.",
    "Chuck Norris counted to infinity using Roman numerals.",
    "Chuck Norris can fold a fitted sheet perfectly.",
    "Chuck Norris can find the end of a circle.",
    "Chuck Norris once made a computer run without power.",
    "Chuck Norris uses pepper spray to spice up his steaks.",
    "Chuck Norris can high-five himself.",
    "Chuck Norris can win a chess game in one move.",
    "Chuck Norris can delete the Recycle Bin.",
    "Chuck Norris once climbed Mount Everest in flip-flops.",
    "Chuck Norris can start a car by yelling at it.",
    "Chuck Norris's GPS follows him.",
    "Chuck Norris can moonwalk forward.",
    "Chuck Norris can unplug a USB drive safely without ejecting it.",
    "Chuck Norris once broke the internet. Literally.",
    "Chuck Norris can touch the bottom of the ocean. From the surface.",
    "Chuck Norris once parallel parked a train.",
    "Chuck Norris once threw a grenade and it returned out of fear.",
    "Chuck Norris can win at rock-paper-scissors with only rock.",
    "Chuck Norris doesn’t cheat death. He wins fair and square.",
    "Chuck Norris can microwave cold air.",
    "Chuck Norris once paused a live stream.",
    "Chuck Norris can use Morse code with a flashlight that's off.",
    "Chuck Norris's dreams are in 4D.",
    "Chuck Norris once drew a perfect circle with an Etch A Sketch.",
    "Chuck Norris can alphabetize soup.",
    "Chuck Norris has a pet rock that fetches.",
    "Chuck Norris once rode a bicycle through a PowerPoint presentation.",
    "Chuck Norris’s bookmarks are actual marks in real books.",
    "Chuck Norris can win hide-and-seek without hiding.",
    "Chuck Norris makes elevators go sideways.",
    "Chuck Norris can speak in italics.",
    "Chuck Norris can fax a sandwich.",
    "Chuck Norris once counted to one. It took him zero seconds.",
    "Chuck Norris's mailbox delivers mail to him.",
    "Chuck Norris once installed Windows on a toaster.",
    "Chuck Norris can play hopscotch on the moon.",
    "Chuck Norris once rebooted the sun.",
    "Chuck Norris makes paper from stone.",
    "Chuck Norris’s cloud storage is actual clouds.",
    "Chuck Norris once made a silent alarm talk.",
    "Chuck Norris’s shoes are afraid to wear out.",
    "Chuck Norris can use a floppy disk to store the internet.",
    "Chuck Norris can organize a mess.",
    "Chuck Norris once signed an unsigned integer.",
    "Chuck Norris can play Jenga with marshmallows.",
    "Chuck Norris once rebooted a sandwich.",
    "Chuck Norris can take a screenshot of a broken screen.",
    "Chuck Norris’s light bulbs turn themselves off to save energy.",
    "Chuck Norris’s autocorrect corrects itself.",
    "Chuck Norris’s watch has no hands. He decides what time it is.",
    "Chuck Norris can turn toast back into bread.",
    "Chuck Norris doesn’t wear glasses. He sees everything.",
    "Chuck Norris’s shadow left him because it couldn’t keep up.",
    "Chuck Norris can do a backflip while standing still.",
    "Chuck Norris once taught Siri to be quiet.",
    "Chuck Norris can peel a banana with one hand. Without touching it."
]



def get_random_joke():
    """Returns a random Chuck Norris joke from the list."""
    return random.choice(CHUCK_NORRIS_JOKES) 